receivers:
  otlp:
    protocols:
      grpc:

exporters:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  otlphttp/traceloop:
    traces_endpoint: https://api.traceloop.dev/v1/traces
    headers:
      Authorization: da233411-b8b1-49ae-a3ca-beaefe673d9e

processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
    traces/traceloop:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/traceloop]
